### ISSUE TITLE
__init__.py needs to have imports for the different sub-modules

### ISSUE THREAD

**Issue by wolfy1339** [quantifiedcode/checkmate#9]
```pytb
Traceback (most recent call last):
  File "manage.py", line 1, in <module>
    from quantifiedcode.settings import settings
  File "/root/quantifiedcode/quantifiedcode/settings/__init__.py", line 1, in <module>
    from .base import * #noqa
  File "/root/quantifiedcode/quantifiedcode/settings/base.py", line 12, in <module>
    from quantifiedcode.helpers.settings import Settings, load_settings
  File "/root/quantifiedcode/quantifiedcode/helpers/settings.py", line 13, in <module>
    from checkmate.settings import Settings as CheckmateSettings
ImportError: No module named checkmate.settings
```
Once I patch `__init__.py `(all of them) with a simple `from . import *`,

```pytb
Traceback (most recent call last):
  File "manage.py", line 2, in <module>
    from quantifiedcode.backend.commands import commands
  File "/root/quantifiedcode/quantifiedcode/backend/commands/__init__.py", line 6, in <module>
    from .server import runserver
  File "/root/quantifiedcode/quantifiedcode/backend/commands/server.py", line 2, in <module>
    from quantifiedcode.app import get_app
  File "/root/quantifiedcode/quantifiedcode/app.py", line 21, in <module>
    from quantifiedcode.backend.app import get_app as get_backend_app
  File "/root/quantifiedcode/quantifiedcode/backend/app.py", line 22, in <module>
    from .api.v1 import routes as routes_v1
  File "/root/quantifiedcode/quantifiedcode/backend/api/v1/__init__.py", line 1, in <module>
    from .routes import routes
  File "/root/quantifiedcode/quantifiedcode/backend/api/v1/routes.py", line 51, in <module>
    from .issue import (
  File "/root/quantifiedcode/quantifiedcode/backend/api/v1/issue.py", line 18, in <module>
    from .forms.issue_status import IssueStatusForm
  File "/root/quantifiedcode/quantifiedcode/backend/api/v1/forms/issue_status.py", line 6, in <module>
    class IssueStatusForm(Form):
  File "/root/quantifiedcode/quantifiedcode/backend/api/v1/forms/issue_status.py", line 9, in IssueStatusForm
    ignore_reason = SelectField(u"Ignore Reason", choices=[(str(Issue.IgnoreReason.false_positive),"false positive"),
AttributeError: type object 'Issue' has no attribute 'IgnoreReason'
```

**Comment by voarsh** [comment]
Same here
